# Generated by Django 3.1.4 on 2021-03-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210224_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='wc',
            field=models.BinaryField(blank=True),
        ),
    ]
